version: '3.2'
services:
  jenkins-devspaces:
    build:
      context: ""
      dockerfile: Dockerfile
    entrypoint: /usr/local/bin/devspaces-entrypoint.sh
    volumes:
    - type: bind
      source: ../../
      target: /data
    ports:
    - "8080:8080" # main web app http port
    - "50000:50000" # agent port
    networks:
    - default
    container_name: jenkins-devspaces

networks:
  default:
